// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_enhanced_figlet from "./routes/api/enhanced-figlet.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_random_ascii_art from "./routes/api/random-ascii-art.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $thanks from "./routes/thanks.tsx";
import * as $AboutModal from "./islands/AboutModal.tsx";
import * as $AsciiGallery from "./islands/AsciiGallery.tsx";
import * as $Dropzone from "./islands/Dropzone.tsx";
import * as $KofiModal from "./islands/KofiModal.tsx";
import * as $TabSwitcher from "./islands/TabSwitcher.tsx";
import * as $TabsIsland from "./islands/TabsIsland.tsx";
import * as $TextToAscii from "./islands/TextToAscii.tsx";
import * as $ThemeIsland from "./islands/ThemeIsland.tsx";
import * as $WelcomeChecker from "./islands/WelcomeChecker.tsx";
import * as $WelcomeModal from "./islands/WelcomeModal.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/enhanced-figlet.ts": $api_enhanced_figlet,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/random-ascii-art.ts": $api_random_ascii_art,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/thanks.tsx": $thanks,
  },
  islands: {
    "./islands/AboutModal.tsx": $AboutModal,
    "./islands/AsciiGallery.tsx": $AsciiGallery,
    "./islands/Dropzone.tsx": $Dropzone,
    "./islands/KofiModal.tsx": $KofiModal,
    "./islands/TabSwitcher.tsx": $TabSwitcher,
    "./islands/TabsIsland.tsx": $TabsIsland,
    "./islands/TextToAscii.tsx": $TextToAscii,
    "./islands/ThemeIsland.tsx": $ThemeIsland,
    "./islands/WelcomeChecker.tsx": $WelcomeChecker,
    "./islands/WelcomeModal.tsx": $WelcomeModal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
